### ISSUE TITLE
How to display images from memory data in Adwaita-Swift?

### ISSUE THREAD

**Issue by lesclaz** [AparokshaUI/adwaita-swift#23]
### Is your feature request related to a problem? Please describe.

I am developing an application with Adwaita-Swift and have encountered the need to display images from memory data (Data). I have searched through the available documentation and examples, but have not found clear guidance or a specific widget in Adwaita-Swift that allows me to do this.

### Describe the solution you'd like

Could you please provide me with some examples or guidance on how to implement the loading and display of images?
Any code examples or recommendations on best practices for handling these cases would be very helpful and appreciated.

### Describe alternatives you've considered

.

### Additional context

.

**Comment by david-swift** [comment]
Since b7aabb0, it's possible to use the following syntax:

```swift
Picture()
    .data(data)
```

Find the documentation for the data modifier [here](https://aparokshaui.github.io/adwaita-swift/documentation/adwaita/picture/data(_:)).

I added the following example to the Demo app:
[Screencast from 2024-04-21 11-49-50.webm](https://github.com/AparokshaUI/adwaita-swift/assets/106754840/c97b69f0-36ae-4780-82d3-c3b46494dcbc)

The code for the example is available [here](https://github.com/AparokshaUI/adwaita-swift/blob/b7aabb09667a63a18f7d6148a6012b7ec0144c7f/Tests/PictureDemo.swift#L28)

If you miss a certain option to customize the appearance of the image or similar, feel free to open another issue. I'm very happy about those requests, thank you so much!
