### ISSUE TITLE
libadwaita version dependency

### ISSUE THREAD

**Issue by felixf4xu** [AparokshaUI/adwaita-swift#25]
### Describe the solution you'd like

Use libadwaita in system default version (like in Ubuntu 22's, libadwaita is v1.1.0)

--

or, is it possible to conditionally compile this project by libadwaita version?

### Describe alternatives you've considered

I tried to compile this project and found out that libadwaita version >= 1.4 (at least) is used.

If the locally installed `libadwaita` is not new, many `CAdw` functions are not available, like
```sh
error: cannot find 'adw_navigation_view_pop' in scope
```

### Additional context

my libadwaita version is: 1.3.2

**Comment by david-swift** [comment]
I really recommend developing either inside a Flatpak, take a look at the [ŧemplate repository](https://github.com/aparokshaui/adwaitatemplate) with a sample Flatpak manifest, or using [Homebrew](https://brew.sh/) as a package manager. Using the latest GNOME runtime in the Flatpak, you always get the latest libadwaita version, and I try not to switch to the latest Libadwaita version faster than Homebrew.

I don't think there's a simple way to check the installed version and define which functions are available based on this (it is possible for Swift or platform versions, but not for system libraries).

Libadwaita 1.5 is required in order to compile.
