### ISSUE TITLE
Some interface should check available

### ISSUE THREAD

**Issue by CmST0us** [AparokshaUI/adwaita-swift#3]
Thanks to your great work I really need this!
I am trying to run demo on my ubuntu 22.04. I meet some problem, the version of libadwaita on Ubuntu 22.04 is 1.1, but Adwaita seems uses some newer interface.
I think if there should be a method to control interface available?

**Comment by david-swift** [comment]
Thanks for opening this issue! I suggest to develop apps inside a Flatpak, you can use the template's [Flatpak manifest](https://github.com/AparokshaUI/AdwaitaTemplate/blob/main/io.github.AparokshaUI.AdwaitaTemplate.json) as a starting point. GNOME Builder has a very good integration with Flatpaks (in case you don't want to use the command line).

The problem is that, even if auto generation would be executed on the app developer's device, matching the available version, there is still manually written code in this library that _depends_ on auto-generated code or that directly _calls_ libadwaita functions. This code enables a more SwiftUI-like approach to certain widgets, such as `NavigationView`. Code for windows and menus isn't auto-generated as well. These parts wouldn't compile with older libadwaita versions.

Currently, the required libadwaita version is 1.4, but I'll add features requiring 1.5 as soon as it is available (e.g. the new dialogs). I really recommend using `flatpak-builder` directly or indirectly using GNOME Builder.

**Comment by CmST0us** [comment]
Thanks for your advice! 😃
I am going to play with adwaita

**Comment by david-swift** [comment]
Have fun! Don't hesitate to open issues for reporting problems or suggesting ideas! You can also ask questions in the GitHub discussions.

**Comment by CmST0us** [comment]
BTW: I am working on swift 32bit armhf toolchain. And I am going to run this demo on my 32-bit stm32mp157 platform.
So is there any limitation that Adwaita must run on 64-bit platform?

**Comment by david-swift** [comment]
I never tried that, but if Swift 5.8 (or higher) and libadwaita 1.4 work on 32-bit platforms, this package should as well.

**Comment by CmST0us** [comment]
OK I am really interesting with it, when i run adwaita on my 32bit platform. I will open a discussion😁

**Comment by david-swift** [comment]
Hi @CmST0us, how is using Adwaita for Swift on your 32-bit platform working?

**Comment by CmST0us** [comment]
I am working on yocto now.

**Comment by CmST0us** [comment]
I am working on yocto now.
First, I need to build libadwaita 32-bit on yocto, and run libadwaita-demos.
With yocto, I can easily get a toolchain with libadwaita.
Than with this toolchain, i can get my swift 32-bit toolchain work to build `adwaita-swift`.

For now, i still working on how to build libadwait with yocto.

And other way is to strip unavailable interface, in order to build with libadwaita-1.1 (which is the ubuntu version).
May be it's the fastest way to get `adwaita-swift` run on 32-bit platform. (I already have ubuntu 32-bit swift toolchain)

**Comment by david-swift** [comment]
Thanks for the detailed answer! It might be useful for others trying this.
