### ISSUE TITLE
Separated list style do not apply

### ISSUE THREAD

**Issue by iDevPro** [AparokshaUI/adwaita-swift#48]
### Describe the bug

Try to append functionality for List

```style("boxed-list-separate", active: active)```

doesn't work for list at all :(

### To Reproduce

1. create a new function inside List.swift like:
```swift
/// https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/style-classes.html#boxed-lists-cards
public func separatedBoxedList(_ active: Bool = true) -> View {
        style("boxed-list-separate", active: active)
    }
```

2. apply it to List object in code
```swift
     List(model.items) { item in ... 
            Text(item.title)
                .padding()
     }
     . separatedBoxedList()
```

3. run app

### Expected behavior

A separated style list shown 

![boxed-lists-separate-dark](https://github.com/user-attachments/assets/804b72b4-2b8b-4950-b537-364c7dddca6c)

**Comment by david-swift** [comment]
This is a new feature in Libadwaita which is not yet in a stable release (will ship with GNOME 47 I guess). In case you're in a Flatpak, you could change the `runtime-version` to `master`, otherwise you would have to install the development version of GNOME on your system. Once GNOME 47 is stable, I'll add type-safe support for this style so you won't have to do it yourself. If you want to build for GNOME 46, you would have to use [`ForEach`](https://aparokshaui.github.io/adwaita-swift/documentation/adwaita/foreach) and apply the [card style](https://aparokshaui.github.io/adwaita-swift/documentation/adwaita/view/card(_:)) to the children. Hope that helps!
